### ISSUE TITLE
TypeScript declarations specify non-existent named export

### ISSUE THREAD

**Issue by sachinahya** [fastify/fastify-express#90]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Plugin version

2.0.0

### Node.js version

16.14.2

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

The types describe a named export of `fastifyExpress` but there is no such export. The plugin is only exported via `module.exports`.

As such, TS reports this as valid:

```
import { fastifyExpress } from '@fastify/express';
```

But it fails at runtime:

```
/Users/sachinahya/code/play/vite-react-18-ssr-boilerplate/node_modules/avvio/boot.js:207
    throw new AVV_ERR_PLUGIN_NOT_VALID(typeof plugin)
          ^
AvvioError [Error]: Plugin must be a function or a promise. Received: 'undefined'
    at assertPlugin (/Users/sachinahya/code/play/vite-react-18-ssr-boilerplate/node_modules/avvio/boot.js:207:11)
    at Boot._addPlugin (/Users/sachinahya/code/play/vite-react-18-ssr-boilerplate/node_modules/avvio/boot.js:240:12)
    at Boot.use (/Users/sachinahya/code/play/vite-react-18-ssr-boilerplate/node_modules/avvio/boot.js:216:25)
    at Object.server.<computed> [as register] (/Users/sachinahya/code/play/vite-react-18-ssr-boilerplate/node_modules/avvio/boot.js:40:14)
    at createServer (/Users/sachinahya/code/play/vite-react-18-ssr-boilerplate/src/server/server-dev.ts:20:13)
    at Object.<anonymous> (/Users/sachinahya/code/play/vite-react-18-ssr-boilerplate/src/server/server-dev.ts:103:6)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/Users/sachinahya/code/play/vite-react-18-ssr-boilerplate/node_modules/ts-node/src/index.ts:1597:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/sachinahya/code/play/vite-react-18-ssr-boilerplate/node_modules/ts-node/src/index.ts:1600:12) {
  code: 'AVV_ERR_PLUGIN_NOT_VALID'
}
```

### Steps to Reproduce

Register the plugin using a named export and it produces the error above.

```ts
import { fastifyExpress } from '@fastify/express';

const app = fastify();
await app.register(fastifyExpress);
```

### Expected Behavior

TypeScript should report an error specifying that `@fastify/express` does not export `fastifyExpress`.

**Comment by kibertoad** [comment]
Thank you for the report! Would you consider sending a fix PR?
